Compatible with Symfony 3.2 incl. WebProfiler tab
phpro/soap-client-sf2-bridge pull request #2
Opened 2017-01-08 17:32 UTC by insekticid

Min PHP version set to 5.5.9

2017-01-09 07:08 UTC, veewee commented
Hello @insekticid, 

Thanks for the PR! The next version of the soap-client will be PHP ^7.0 so you can bump to that version.
@janvernieuwe: Can you review this PR?

2017-01-09 13:07 UTC, janvernieuwe requested changes
Hi @insekticid,

Thanks again for your PR.

I have added some remarks, mainly for consistency between the request and response.

2017-01-09 13:07 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/DataCollector/SoapCallCollector.php
> +    public function getCount()
Can you please add a test to the spec and a docblock to this function.

2017-01-09 13:07 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/Resources/views/Toolbar/index.html.twig
> +                        <div>{{ request.requestBody|nl2br }}</div>
The request and response are formatted, please use < pre > tags in stead of nl2br, otherwise we'll loose the alignment of the xml elements.

2017-01-09 13:07 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/Resources/views/Toolbar/index.html.twig
> +                            <div>{{ request.responseBody }}</div>
Please add < pre > tags here

2017-01-09 13:07 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/Resources/views/Toolbar/index.html.twig
> +                        <a href="#" class="sf-toggle link-inverse text-small" data-toggle-selector="#soap-response-{{ loop.index }}" data-toggle-alt-content="Hide response"{{ profiler_markup_version
It seems useful to me that the response is always shown as well.
Please make the response consistent with the request (hide the headers by default, and show the content)

2017-01-09 13:33 UTC, veewee requested changes

2017-01-09 13:33 UTC, veewee commented on composer.json
> +    {
To make sure that every author gets credit for their code, we use this [contributors list](https://github.com/phpro/soap-client-sf2-bridge/graphs/contributors) as the single source of truth. This way we can keep the `composer.json` file clean and we don't have to manage the contributors list manually. Can you remove these lines? Thanks!

2017-01-09 17:00 UTC, insekticid commented on src/Phpro/SoapClient/BridgeBundle/Resources/views/Toolbar/index.html.twig
> +                            <div>{{ request.responseBody|nl2br }}</div>
this nl2br needs to be here, otherwise xml response could be unindented

2017-01-09 17:53 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/Resources/views/Toolbar/index.html.twig
> +                            <div>{{ request.responseBody|nl2br }}</div>
All requests and responses are ran trough DOMDocument for formatting in the SoapCall class.

2017-01-09 18:06 UTC, insekticid commented
Fixed, I missed <pre> in getResponseBody output

2017-01-10 07:53 UTC, veewee approved these changes

2017-01-12 11:17 UTC, insekticid commented
What are you waiting for?

2017-01-12 11:24 UTC, janvernieuwe approved these changes

2017-01-12 11:30 UTC, insekticid commented
after PULL merge, there is another problem after soap call exception - impossible to render web profiller
I created patch, so new pull request after merge

2017-01-12 14:00 UTC, merged

2017-01-12 14:00 UTC, veewee commented
HI @insekticid,

Thanks for your PR. We are going to merge it in and tweak the layout a bit.