$timing is undefined after soap call exception
phpro/soap-client-sf2-bridge pull request #4
Opened 2017-01-12 16:16 UTC by insekticid

$requestBody and $responseBody could be empty - DomDocument throws Exception

2017-01-12 16:25 UTC, veewee requested changes
Thanks for the PR. I've added some small remarks to the code.

Can you also add some tests for the changes you made in the spec file?
https://github.com/phpro/soap-client-sf2-bridge/blob/master/spec/Phpro/SoapClient/BridgeBundle/Type/SoapCallSpec.php

This is to guarantee that the class works as expected.

2017-01-12 16:25 UTC, veewee commented on src/Phpro/SoapClient/BridgeBundle/Type/SoapCall.php
> +        if ($this->timing) {
Maybe something like this is shorter:
```php
return $this->timing ?? 0;
```

2017-01-12 16:25 UTC, veewee commented on src/Phpro/SoapClient/BridgeBundle/Type/SoapCall.php
> +        if ($this->requestBody) {
Can you invert the if and add an early return instead?
Is this actually an error, or should the message say something like 'Empty resuest'?

2017-01-12 16:25 UTC, veewee commented on src/Phpro/SoapClient/BridgeBundle/Type/SoapCall.php
> +        if ($this->responseBody) {
Can you invert the if and add an early return instead?
Is this actually an error, or should the message say something like 'Empty response'?

2017-01-12 16:27 UTC, insekticid commented on src/Phpro/SoapClient/BridgeBundle/Type/SoapCall.php
> +        if ($this->responseBody) {
maybe better could be
`try {
$request = new \DOMDocument();
...
return $request->saveXML();
} catch (\Exception $e) {
return $->getMessage();
}`

2017-01-13 09:02 UTC, janvernieuwe commented on src/Phpro/SoapClient/BridgeBundle/Type/SoapCall.php
> +        if ($this->responseBody) {
Definitely a good idea to try-catch the formatting!

2017-04-21 12:20 UTC, janvernieuwe commented
Hi @insekticid,

This PR has been hanging here for a while now, hence my question if you are planning to complete the requested changes?

Thanks in advance!

2017-04-21 12:49 UTC, insekticid commented
done

2017-04-21 13:21 UTC, merged